/* Verified historical return replay; its fills are normalized index units. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./decision-view.js').ReplayControl);else root.MarketObservedView=factory(root.MarketReplayControl);})
(typeof globalThis!=='undefined'?globalThis:this,function(replay){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const modes={no_text:'无文本',keywords:'关键词',reviewed_llm:'复核后 LLM'};
  const roles={aggressive:'激进型',conservative:'保守型',institutional:'机构型'};
  const colors={no_text:'#718096',keywords:'#ce892f',reviewed_llm:'#418bb2'};
  const numeric=n=>typeof n==='number'&&Number.isFinite(n);
  function number(n,d=4,signed=false){if(!numeric(n))return '未存档';const text=n!==0&&Math.abs(n)<.5*10**-d?n.toExponential(2):n.toFixed(d);return(signed&&n>=0?'+':'')+text;}
  const percent=n=>numeric(n)?number(n*100,4)+'%':'未存档';
  const notice=m=>m?`<div class="callout" role="alert">${esc(m)}</div>`:'';
  function timestamp(value){const d=new Date(value);return Number.isNaN(d.getTime())?String(value??''):d.toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})+'（北京时间）';}
  const actionNames={buy:'买入',sell:'卖出',hold:'持有'};
  const reasons={market_signal:'市场判断',text_signal:'文本方向',uncertainty_stress:'不确定性压力',risk_budget_cap:'风险仓位上限',risk_liquidation_priority:'超限优先减仓',confirmation_wait:'等待连续确认',rebalance_wait:'等待再平衡',minimum_trade:'小于交易阈值',risk_liquidation_overrides_turnover:'优先减仓超过换手限制'};
  class ObservedState{
    constructor(){this.catalog=null;this.selectedId=null;this.loadedId=null;this.detail=null;this.condition='reviewed_llm';this.step=1;this.chart='nav';this.factView='reviewed';this.evidenceFocus=null;this.loading=false;this.error='';this.generation=0;}
    begin(id){this.selectedId=id;if(this.loadedId!==id){this.detail=null;this.evidenceFocus=null;}this.loading=true;this.error='';return{id,generation:++this.generation};}
    current(t){return t.generation===this.generation&&t.id===this.selectedId;}
    accept(t,b){if(!this.current(t))return false;if(b.id!==t.id||b.schema!=='platform-observed-experiment-v1'||b.data_kind!=='observed_return_price_taking_replay'||!Object.keys(modes).every(m=>b.paths?.[m]?.trace?.length===b.sessions&&b.explanations?.[m]?.length===b.sessions))throw new Error('历史实验响应与当前归档不一致');if(this.loadedId!==t.id){const first=b.paths.reviewed_llm.trace.findIndex(d=>d.source_active);this.step=first<0?1:first+1;}this.detail=b;this.loadedId=t.id;this.step=Math.max(1,Math.min(this.step,b.sessions));this.loading=false;this.error='';return true;}
    fail(t,message){if(!this.current(t))return false;this.loading=false;this.error=message;return true;}
    clear(){this.detail=null;this.selectedId=null;this.loadedId=null;this.loading=false;this.error='';this.evidenceFocus=null;this.generation++;}
  }
  function renderLibrary(catalog,state){
    if(!catalog)return '<section class="panel case-empty">正在核验本机历史行情实验…</section>';
    if(!catalog.available)return `<section class="panel case-empty">${esc(catalog.message)}<p>本页读取已完成的真实收益回放；新建情景实验可在实验空间继续使用。</p></section>`;
    return `<div class="observed-library">${catalog.experiments.map(e=>`<button class="observed-archive ${state.selectedId===e.id?'active':''}" data-observed-select="${esc(e.id)}" aria-pressed="${state.selectedId===e.id}"><span class="badge blue">真实历史收益</span><strong>${esc(e.label)}</strong><span>${esc(e.start_date)} — ${esc(e.end_date)} · ${esc(e.sessions)} 个交易日 · ${esc(e.agent_decisions)} 次决策</span></button>`).join('')}</div>`;
  }
  function controls(state){return `<div class="observed-controls"><div class="segmented" role="group" aria-label="历史实验信息条件">${Object.entries(modes).map(([m,label])=>`<button class="${state.condition===m?'active':''}" data-observed-condition="${m}" aria-pressed="${state.condition===m}">${label}</button>`).join('')}</div><span>切换归档条件，查看同一天的决策与账户</span></div>`;}
  function renderSource(b,focus){
    return `<section class="panel" id="observed-source"><div class="panel-header"><div><h2>原始问答与发布时间</h2><p class="panel-subtitle">${esc(timestamp(b.case.available_at))} · 日期精度，按日结束可见</p></div><span class="badge neutral">公司回复建立事实</span></div><div class="summary-content">${b.case.segments.map(segment=>{const chars=Array.from(segment.text);let text=esc(segment.text);if(focus?.source===segment.source&&Number.isInteger(focus.start)&&Number.isInteger(focus.end)&&focus.start>=0&&focus.end<=chars.length&&focus.end>focus.start&&chars.slice(focus.start,focus.end).join('')===focus.quote)text=esc(chars.slice(0,focus.start).join(''))+`<mark id="observed-source-mark">${esc(focus.quote)}</mark>`+esc(chars.slice(focus.end).join(''));return `<div class="case-source-segment"><h3>${segment.source==='question'?'投资者提问':'公司回复'}</h3><p>${text}</p></div>`;}).join('')}</div></section>`;
  }
  function renderFacts(b,state){
    const raw=state.factView==='raw',facts=raw?b.model.normalized.facts:b.review.reviewed_record.facts;
    const kindNames={approval_uncertainty:'审批不确定',static_information:'静态背景',information_gap:'信息缺失',completed_transaction:'交易陈述',regulatory_constraint:'监管约束',other:'未量化事项'};
    return `<section class="panel case-facts-panel"><div class="panel-header"><div><h2>DeepSeek 提取与逐条复核</h2><p class="panel-subtitle">${esc(b.model.model)} · 实际请求完成于 ${esc(timestamp(b.model.finished_at_utc))} · 单一助手来源复核</p></div><div class="segmented" role="group" aria-label="历史实验事实版本">${[['reviewed','复核后'],['raw','原始提取']].map(([v,label])=>`<button data-observed-facts="${v}" class="${state.factView===v?'active':''}" aria-pressed="${state.factView===v}">${label}</button>`).join('')}</div></div><div class="summary-content"><div class="case-facts-list">${facts.map((f,i)=>`<article class="case-fact"><span class="badge neutral">${esc(kindNames[f.kind]||f.kind)}</span><p>${esc(f.claim)}</p>${f.evidence.map((e,j)=>`<blockquote>${esc(e.quote)}<small>字符 [${e.start}, ${e.end}) <button class="subtle-link" data-observed-fact="${i}" data-observed-part="${j}">定位原文</button></small></blockquote>`).join('')}<details><summary>查看复核理由</summary><p>${esc(b.review.checks.find(c=>c.fact_index===i)?.notes||'未存档')}</p></details></article>`).join('')}</div><details class="observed-raw"><summary>查看当时模型的完整原始返回</summary><pre>${esc(b.model.raw_response)}</pre></details><p class="case-help">引文和归档已核验。这是开发案例，单一助手复核不构成独立准确率验证；读取不重新调用模型。</p></div></section>`;
  }
  function renderSummary(b){
    const trace=b.paths.no_text.trace,first=b.paths.reviewed_llm.trace.find(d=>d.source_active);
    return `<div class="metrics-strip">${[['历史窗口',`${b.sessions} 个交易日`,`${trace[0].trade_date} — ${trace.at(-1).trade_date}`],['Agent 决策',`${b.verification.agent_decisions} 次`,'三条件 × 三类预设策略'],['文本首次作用',first?.trade_date||'未存档',`作用 ${b.information_duration_steps} 个决策日`],['归档核验','已通过','账务复算 · 精确离线重放']].map(([label,v,foot])=>`<div class="metric"><div class="metric-label">${esc(label)}</div><div class="metric-value observed-metric-value">${esc(v)}</div><div class="metric-foot">${esc(foot)}</div></div>`).join('')}</div><section class="panel"><div class="panel-header"><div><h2>三条件完整结果</h2><p class="panel-subtitle">每类初资 ${number(b.parameters[0].initial_cash,0)} · 单边费率 ${percent(b.fee_rate)} · 收益已计费用</p></div><span class="badge neutral">预设策略 · 单案例开发</span></div><div class="table-wrap observed-results"><table><thead><tr><th>策略 / 条件</th><th>收益</th><th>相对无文本</th><th>最大回撤</th><th>成交决策日</th><th>费用</th></tr></thead><tbody>${Object.entries(roles).map(([role,label])=>b.comparison.filter(r=>r.role===role).map((r,i)=>`<tr><td>${i===0?`<strong>${label}</strong> · `:''}${modes[r.condition]}</td><td>${number(r.return_pct)}%</td><td>${number(r.delta_return_pp,4,true)} pp</td><td>${number(r.max_drawdown_pct)}%</td><td>${number(r.trades,0)}</td><td>${number(r.fees,2)}</td></tr>`).join('')).join('')}</tbody></table></div></section>`;
  }
  function chart(b,state,p){
    const values=Object.keys(modes).flatMap(m=>b.paths[m].trace.map(d=>state.chart==='nav'?d.agents[p.name].closing_wealth/p.initial_cash:d.agents[p.name].closing_weight));
    if(!values.every(numeric))return '<p class="case-help">图形字段未完整归档</p>';
    const low=Math.min(...values),high=Math.max(...values),pad=Math.max((high-low)*.12,.005),min=low-pad,max=high+pad;
    const x=i=>40+i*300/Math.max(1,b.sessions-1),y=v=>168-(v-min)*136/(max-min);
    const trace=b.paths.reviewed_llm.trace,active=trace.map((d,i)=>d.source_active?i:-1).filter(i=>i>=0);
    const shade=active.length?`<rect x="${x(active[0])}" y="24" width="${Math.max(3,x(active.at(-1))-x(active[0]))}" height="144" fill="var(--teal-soft)"/>`:'';
    const series=Object.keys(modes).map(m=>{const v=b.paths[m].trace.map(d=>state.chart==='nav'?d.agents[p.name].closing_wealth/p.initial_cash:d.agents[p.name].closing_weight);return `<path d="${v.map((n,i)=>`${i?'L':'M'}${x(i).toFixed(2)},${y(n).toFixed(2)}`).join(' ')}" fill="none" stroke="${colors[m]}" stroke-width="${m===state.condition?2.5:1.5}" opacity="${m===state.condition?1:.7}"/><circle cx="${x(state.step-1)}" cy="${y(v[state.step-1])}" r="3" fill="${colors[m]}"/>`;}).join('');
    const ticks=[min,(min+max)/2,max].map(v=>`<line x1="40" x2="340" y1="${y(v)}" y2="${y(v)}" stroke="var(--line)"/><text x="34" y="${y(v)+3}" text-anchor="end">${state.chart==='nav'?number(v,2):number(v*100,1)+'%'}</text>`).join('');
    return `<div class="observed-chart"><h3>${roles[p.role]}</h3><svg viewBox="0 0 365 205" role="img" aria-label="${roles[p.role]}${state.chart==='nav'?'净值':'持仓比例'}，三条件历史路径">${shade}${ticks}${series}<line x1="${x(state.step-1)}" x2="${x(state.step-1)}" y1="22" y2="170" stroke="var(--teal)" stroke-dasharray="3 3"/><text x="40" y="194">${trace[0].trade_date.slice(5)}</text><text x="340" y="194" text-anchor="end">${trace.at(-1).trade_date.slice(5)}</text></svg></div>`;
  }
  function renderCharts(b,state){return `<section class="panel observed-chart-panel"><div class="panel-header"><div><h2>真实收益下的账户与仓位</h2><p class="panel-subtitle">浅色区域为文本作用期；竖线为当前回放日。行情相同，账户由各自交易形成。</p></div><div class="segmented" role="group" aria-label="历史实验图形指标">${[['nav','账户净值'],['weight','持仓比例']].map(([key,label])=>`<button data-observed-chart="${key}" class="${state.chart===key?'active':''}" aria-pressed="${state.chart===key}">${label}</button>`).join('')}</div></div><div class="observed-legend">${Object.entries(modes).map(([m,label])=>`<span><i style="background:${colors[m]}"></i>${label}</span>`).join('')}</div><div class="observed-chart-grid">${b.parameters.map(p=>chart(b,state,p)).join('')}</div></section>`;}
  function renderClock(b,state){
    const day=b.paths[state.condition].trace[state.step-1];
    return `<div class="case-clock-grid">${[['决策交易日',day.trade_date],['信息截点',day.signal_cutoff_date],['执行参考日',day.execution_reference_date],['原文状态',!day.source_visible?'尚未可见':day.source_active?'作用期内':'作用期已结束']].map(([label,v])=>`<div><small>${label}</small><strong>${esc(v)}</strong></div>`).join('')}</div><div class="observed-inputs"><span>方向输入 <strong>${number(day.text_signal,2,true)}</strong></span><span>不确定性 <strong>${number(day.text_uncertainty,2)}</strong></span><span>当日实现收益 <strong>${percent(day.observed_return)}</strong>（决策后计入）</span></div><p class="case-help">${state.condition==='no_text'?'无文本条件不使用原文。':'方向与不确定性是预先声明的数值映射。'}历史价格不受 Agent 交易影响，执行按前一收盘参考指数；持仓与订单为归一化指数单位。</p>`;
  }
  function renderDecisions(b,state){
    const day=b.paths[state.condition].trace[state.step-1],base=b.paths.no_text.trace[state.step-1],explanations=b.explanations[state.condition][state.step-1].agents;
    return `<div class="observed-decision-grid">${b.parameters.map(p=>{const r=day.agents[p.name],control=base.agents[p.name],e=explanations[p.name];return `<article class="observed-decision"><div class="observed-decision-heading"><h3>${roles[p.role]}</h3><span class="badge neutral">${actionNames[r.decision.action]||esc(r.decision.action)}</span></div><div class="observed-score"><small>本步判断分值</small><strong>${number(e.combined_score,4,true)}</strong><p>市场 ${number(e.market_contribution,4,true)} · 文本 ${number(e.text_direction_contribution,4,true)} · 不确定性 ${number(e.uncertainty_contribution,4,true)}</p></div><table><thead><tr><th></th><th>所选条件</th><th>无文本</th></tr></thead><tbody>${[['目标仓位',percent(r.decision.target_weight),percent(control.decision.target_weight)],['请求单位',number(r.decision.requested_shares,4),number(control.decision.requested_shares,4)],['成交单位',number(r.filled_shares,4),number(control.filled_shares,4)],['收盘持仓',percent(r.closing_weight),percent(control.closing_weight)],['本步费用',number(r.fees_paid,2),number(control.fees_paid,2)]].map(([label,a,c])=>`<tr><th>${label}</th><td>${a}</td><td>${c}</td></tr>`).join('')}</tbody></table><div class="observed-reasons">${r.decision.reason_codes.map(c=>`<span class="badge neutral">${esc(reasons[c]||c)}</span>`).join('')}</div><div class="observed-decision-evidence"><small>本步实际使用的文本依据</small>${e.text_evidence_used.length?e.text_evidence_used.map((q,i)=>`<blockquote>${esc(q.quote)}<button class="subtle-link" data-observed-receipt="${esc(p.name)}" data-observed-part="${i}">定位原文</button></blockquote>`).join(''):'<p>本步没有文本数值贡献。</p>'}</div></article>`;}).join('')}</div><p class="case-help">来源解释由归档输入与登记参数核算，原始决策记录一并保留。两条件账户可能已不同，所示差异包含此前交易影响。</p>`;
  }
  function renderDetail(b,state){
    if(!b)return notice(state.error)+`<section class="panel case-empty">${state.loading?'正在核验所选历史实验…':'选择一个已归档的历史行情实验。'}</section>`;
    return notice(state.error?state.error+'。保留上次已读取归档，当前核验状态未更新。':'')+notice(state.loading?'正在重新核验归档，当前显示上次读取结果。':'')
      +`<div class="case-detail-heading"><div><h2>${esc(b.label)}</h2><p class="case-help">真实公司回复 · 真实历史收益 · 简化成交回放</p></div><a class="btn" href="/api/platform/observed-experiments/${encodeURIComponent(b.id)}/export">导出完整归档与解释</a></div>`
      +renderSummary(b)+controls(state)+renderCharts(b,state)
      +`<section class="panel observed-replay"><div class="summary-content">${replay.render({id:'observed-step',step:state.step,title:'同一天决策与来源',label:'选择历史实验回放日',unit:'日',context:`${modes[state.condition]} 对照无文本 · ${b.case.stock_code}`,rows:b.paths.reviewed_llm.trace.map(d=>({date:d.trade_date,visible:d.source_visible,active:d.source_active}))})}<div id="observed-clock">${renderClock(b,state)}</div><div id="observed-decisions">${renderDecisions(b,state)}</div></div></section>`
      +renderSource(b,state.evidenceFocus)+renderFacts(b,state)
      +'<p class="case-help observed-boundary">单案例开发实验，未训练真实投资者行为。数值映射与持续期是声明假设；成交尚未考虑整手、涨跌停排队、滑点、盘口和市场冲击，结果不能证明预测有效性或策略普遍优劣。</p>';
  }
  return{ObservedState,renderLibrary,renderDetail,renderClock,renderDecisions,renderCharts,renderSource,renderFacts,number};
});
